name: Code Coverage
on:
  push:
    branches:
      - master
      - coverage
jobs:
  build:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install_dependencies
        run: |
         sudo apt-get update -y -qq
         sudo apt-get install libsdl2-dev libsdl2-image-dev nlohmann-json3-dev lcov gcovr
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Run coverage targets
        run: |
          mkdir coverage
          cd coverage
          cmake -DCMAKE_BUILD_TYPE="Coverage" ../
          make $(cmake --build . --target help | grep coverage | awk '{printf $NF " "}')
          rm -rf $(ls | grep -v '\_coverage$')
      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-reports
          path: coverage
          retention-days: 1

          
